/// A strategy archetype generated by the Heuristic Engine for a given kingdom.
enum ArchetypeKind {
  engineBuilding,
  bigMoney,
  aggressiveControl,
  trashToVictory,
  altVictory,
  mirrorMatch,   // heavily attack-mirrored kingdoms
}

extension ArchetypeKindExtension on ArchetypeKind {
  String get displayName {
    switch (this) {
      case ArchetypeKind.engineBuilding:     return 'Engine Building';
      case ArchetypeKind.bigMoney:           return 'Big Money / Slog';
      case ArchetypeKind.aggressiveControl:  return 'Aggressive / Control';
      case ArchetypeKind.trashToVictory:     return 'Trash-to-Victory';
      case ArchetypeKind.altVictory:         return 'Alt-Victory Path';
      case ArchetypeKind.mirrorMatch:        return 'Mirror Match';
    }
  }

  String get iconAsset {
    switch (this) {
      case ArchetypeKind.engineBuilding:     return 'assets/images/archetype_engine.png';
      case ArchetypeKind.bigMoney:           return 'assets/images/archetype_bigmoney.png';
      case ArchetypeKind.aggressiveControl:  return 'assets/images/archetype_attack.png';
      case ArchetypeKind.trashToVictory:     return 'assets/images/archetype_trash.png';
      case ArchetypeKind.altVictory:         return 'assets/images/archetype_victory.png';
      case ArchetypeKind.mirrorMatch:        return 'assets/images/archetype_mirror.png';
    }
  }
}

/// A fully realized archetype with description and tips.
class StrategyArchetype {
  final ArchetypeKind kind;

  /// Short headline shown as a card title.
  final String headline;

  /// 2-4 sentence description of the strategy for this specific kingdom.
  final String description;

  /// Bullet-point tips tailored to the specific cards in this kingdom.
  final List<String> tips;

  /// The cards from the kingdom that most strongly trigger this archetype.
  final List<String> keyCardNames;

  /// Strength score 0.0–1.0 used to sort archetypes (strongest first).
  final double strength;

  const StrategyArchetype({
    required this.kind,
    required this.headline,
    required this.description,
    required this.tips,
    required this.keyCardNames,
    required this.strength,
  });
}
